fte-team/fteqw

- plugins/plugin.c
I wanted to fool around with bullet, and it failed to build.
Since Bullet is written in C++, it causes this to fail to build, since we're returning `bool` instead of `qboolean`. This ensures that doesn't happen. This is done in a few other places in the engine, wonder why not here.
> [Minor] Fix plugin.c failing when building Bullet Plugin

- engine/client/renderer.c
Other sourceports such as Quakespasm define this as a cheat, or rather it doesn't work in multiplayer. We should probably do the same here as it's a debugging feature anyway. This addresses #9
> Make r_showbboxes a cheat CVAR

- engine/client/cl_ents.c
Resolves #186
Fix given by @Shpoike
> Fix BBoxes not visible when RTLights are used.

- engine/client/m_single.c
Resolves #142
This only affects the menu, so if someone REALLY wants to be a spectator in single-player, they can do so with console commands.
> Fix Spectator Singleplayer mode

- engine/client/cl_ents.c
Resolves #157 
I am not too happy with this fix, and there is probably a more correct way of solving this, as noted in the comment.
`renderscene` already calls `R2D_Flush`, but it's not guaranteed to be a poly flush at that point.
But, explicitly doing poly flushes in `renderscene` does not seem to achieve any result.
I have ran out of ideas, and this is the only thing that yielded results.
> Fix the clash between BBoxes and R_Polygons

- iqm/iqm.cpp
- iqm/util.h
According to the IQM file spec: ( http://sauerbraten.org/iqm/iqm.txt )
> // ofs_* fields are relative to the beginning of the iqmheader struct
> // ofs_* fields must be set to 0 when the particular data is empty
> // ofs_* fields must be aligned to at least 4 byte boundaries
However, the FTEIQM tool was producing IQM files where the various fields were _not_ correctly aligned to 4 bytes.
This was causing problems when attempting to port IQM to non-x86 platforms that refuse to read certain data structures at unaligned memory locations.
This fix adds padding to ensure that the IQM fields are 4-byte aligned, and thus compliant to IQM spec.
> FTEIQM Tool Fix for unaligned IQM *_ofs fields

- engine/Makefile
Should fix the emscripten builds failing to build, etc.
> Use zlib fossils directory for permalinked releases of zlib.

- engine/gl/gl_hlmdl.c
- engine/gl/model_hl.h
Half-Life models did not have these flags, but games/mods starting in 2003 and later (Day of Defeat, Condition Zero etc.) use these for plants, trees, cars and anything else desiring masked textures.
> Handle masked textures from post-release Half-Life MDL files.

- engine/client/cl_screen.c
- engine/client/sbar.c
* Hides centerprint when opening teamscores just like with regular scores.
* Avoids printing zeros in tdm/ctf columns for score-less spectators.
> Scoreboard enhancements

- engine/client/m_mp3.c
- engine/client/roq.h
- engine/client/roq_read.c
This fixes color-smearing artifacts on movement (caused by uneven motion vectors not being correctly applicable on half-resolution UV-buffers) and makes RoQ-video directly uploadable as texture.
YUV-to-RGB-conversion is now done only when receiving new codebooks in the RoQ stream, which is a lot less data to be RGB-converted per-frame.
> RoQ decoder: Work on RGBA-data interenally instead of YUV420-data

- engine/server/sv_send.c
Previously it would only deliver if:
(a) you were spectating no one
(b) player-0 was getting messages (which you'd then incorrectly receive)
> Deliver _ONE messages to correct spectator(s)

- engine/client/m_mp3.c
Fixed a slight typo in the description for the `capturedemo` command.
> Fix typo in capturedemo command

- engine/client/render.h
- engine/client/view.c
- engine/gl/gl_rmain.c
- engine/shaders/Makefile
- engine/shaders/generatebuiltinsl.c
- engine/shaders/glsl/postproc_panini.glsl
- engine/vk/vk_init.c
- quakec/menusys/menu/options_effects.qc
currently fteqw labels stereographic as panini (well, "pannini"), but stereographic and panini aren't the same projection, panini keeps vertical lines.
i just copied the facemasks from stereographic. it never shows any unrendered areas but the values can probably get changed.
the ffov values are still wrong but they're wrong for every projection. 180 is a perfect side to side 180 degrees but above that is too low and below that is too high.
vertical lines stay vertical, horizontal lines bend. 180 degree fov pictured:
> add panini projection

- quakec/csaddon/src/editor_lights.qc
Modernizes the add light functionality of csaddon to use dynamiclight_spawnstatic and fixes the issue that was causing the first 32 lights to not work  on 64x builds.
First pr ever, please, be gentle. :D
> Utilize dynamiclight_spawnstatic on csaddon and fixes a problem with spawning lights on x64 builds

- engine/server/pr_q1qvm.c
- engine/server/progs.h
- engine/server/sv_ents.c
The lower bits are used for engine metadata and was not trimmed when SendEntity was invoked in the QVM case.
Additionally the result of SendEntity was fetched with the assumption of a traditional QC VM running which caused a crash. Result is now propagated from either QVM or QC.
> Correct sendflags & result of QVM_SendEntity.

- plugins/hl2/glsl/vmt/refract.glsl
- plugins/hl2/mat_vmt.c
- plugins/hl2/mat_vmt_progs.h
This PR fixes these issues:
1. Refractive (VMT) materials without a tint texture used the normal map as tint
2. Patch textures with insert blocks would not load properly
How to test the fixes:
* For 1: The magnifying glass in HL2s d1_trainstation_05 no longer has the wrong tint
* For the case with tint texture I used the glass box in Portal 2s sp_a3_crazy_box (only visible without physics activated)
* For 2: The leaves in overgrown Portal 2 maps render now. I have not seen insert blocks used anywhere else yet
> HL2: Fix minor VMT issues regarding patch- and refraction shaders

- engine/Makefile
- engine/common/common.c
On [November 29 2022](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3127---112922), the Emscripten setting `STACK_SIZE` was lowered from 5MB to 64kb. FTEQW does not work with a 64kb stack, so I have upped it back to 5MB. Because the FTEQW GitHub runner uses a really old version of Emscripten, I had to use the `TOTAL_STACK` setting (it was renamed to `STACK_SIZE` on [November 8 2022](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3125---110822)).
Tested working with Emscripten 3.1.72-git on my Arch Linux machine.
> Fix for newest Emscripten

- plugins/plugin.c
Allows big-endian plugins to compile
Addresses #325
> Add byteswap functions to plugin.c

- LICENSE
added license file that is mentioned in fteqw_readme.txt but is missing from the repo and master zip on https://fteqw.org
section from fteqw_readme.txt that mentions the 'LICENSE' file
```
8. LICENSE
==========
Copyright (c) 2004-2020 FTE's team and its contributors
Quake source (c) 1999 id Software
FTEQW is supplied to you under the terms of the same license as the
original Quake sources, the GNU General Public License Version 2.
Please read the 'LICENSE' file for details.
```
---
> GH: added LICENSE file

- plugins/cod/codbsp.c
`i` suffix turns literal into rarely used feature of C language: complex numbers. Probably `u` was meant here, as `mn` variable used to find minimal value from the array, and it makes more sense to initialize it to all ones.
See also: https://godbolt.org/z/fEb64e8Y6
> plugins: cod: fix typo that made complex number instead of unsigned int

- engine/qclib/initlib.c
After commit dc010d6ec, loading non-legacy saves (sv_savefmt 1 or 2) would result in players being unable to move. This seems to have been caused by localstack pointer corruption during the save/load process.
The issue seems to have occurred because:
1. Commit dc010d6ec changed localstack from a static array to dynamically allocated memory in the addressable memory region
2. When loading saves, SV_SpawnServer -> Q_InitProgs -> PR_Configure -> PRAddressableFlush would reinitialize all addressable memory
3. The localstack pointer wasn't properly cleared, causing corruption of the stringtable and breaking OP_PUSH pointers stored in saved games
The fix ensures that when addressable memory is flushed, the localstack state is properly cleared. The localstack will be correctly reallocated when …
> Fix save/load bug preventing player movement with sv_savefmt 1/2 (fixes #374)

- engine/qclib/qcc.h
- engine/qclib/qcc_pr_comp.c
- engine/qclib/qccmain.c
Useful to e.g. sync between FTEQCC and DP.
> -Fdumpopcodes: dump the opcodes enum for the selected target.

- engine/gl/gl_rlight.c
If a map is using both deluxemapping and HDR lightmaps, entities appear to flicker as they move around. I changed the surface deluxemap offset to match the others and, with that change in place, entities appear to be lit correctly.
> Fix light point deluxemap offset when using HDR lightmaps

- .gitignore
- plugins/Makefile
For some reason the CMake config forces shared libraries on non-Windows platforms when building Python stuff, preventing linking.
> Fix Bullet Physics plugin not building on Linux (and presumably other non-Windows platforms)

- CMakeLists.txt
Yeah, the -march=native doesn't work on ppc64, so a condition is placed to handle that.
> Make it build on ppc64 and ppc64le cpu architectures while using cmake

- engine/client/cl_screen.c
- engine/client/render.h
- engine/client/view.c
- engine/common/q1bsp.c
Run the "mod_buildcubemaps" command to automatically build cubemaps for each env_cubemap present in the map. It also creates the BSPX lump, if necessary. Users still have to set things like "sv_nopvs" and "r_drawentities" to their own liking. I didn't wanna send commands to the server because that'd probably require some terrible hacks.
The resulting screenshots follow the naming scheme used by BSPX_LoadEnvmaps, so they're loaded automatically the next time the map is loaded. I ran tests where the command would stuff "vid_restart" afterward. If that sounds like a good convenience feature, I can reimplement that functionality.
> Automatic cubemap building
